sudo: false
language: node_js
node_js:
  - '5.1'
  - '4.2'
  - '0.12'
addons:
  firefox: "42.0"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
